Update java & lib versions, use confluentinc images in docker-compose, add devcontainer/codespace configuration
loicmathieu/dojo-quarkus-mp-messaging pull request #8
Opened 2023-10-31 12:42 UTC by RemiEven

2023-11-06 11:29 UTC, loicmathieu commented
@RemiEven, thanks for the PR.
As there is a lot of files to review, can you explain how you migrate the Quarkus version? Do you use the quarkus tooling? In this case I'll know that it's OK and didn't review everything ;)

2023-11-06 14:04 UTC, RemiEven commented
Hi @loicmathieu !

Actually I generated new up-to-date quarkus projects with maven, then modified them to add the "business" part of the code, and tried to limit the conflicts with the existing files

A bit convoluted but with my very limited knowledge of quarkus it seemed easier that way!

2023-11-07 09:34 UTC, loicmathieu requested changes

2023-11-07 09:34 UTC, loicmathieu commented on order-api/pom.xml
> +  <groupId>org.acme</groupId>
Please keep the same groupId as before

2023-11-07 09:34 UTC, loicmathieu commented on order-enhancer/pom.xml
> +  <groupId>org.acme</groupId>
Please keep the same groupId as before

2023-11-07 09:34 UTC, loicmathieu commented on search-api/pom.xml
> +  <groupId>org.acme</groupId>
Please keep the same groupId as before

2023-11-07 12:06 UTC, loicmathieu approved these changes
LGMT, thanks

2023-11-07 12:06 UTC, merged